USE biblioteca_murilo;


SELECT AUTOR.*
FROM AUTOR
INNER JOIN AUTOR_LIVRO on AUTOR.ID_AUTOR = AUTOR_LIVRO.FK_AUTOR
WHERE AUTOR_LIVRO.FK_AUTOR IN (
SELECT ISBN FROM LIVRO WHERE TITULO = "Aventuras no Espaço");


SELECT LIVRO.*
FROM LIVRO
INNER JOIN AUTOR_LIVRO ON LIVRO.ISBN = AUTOR_LIVRO.fk_livro
WHERE AUTOR_LIVRO.fk_autor IN (
	SELECT ID_AUTOR FROM AUTOR WHERE NOME_AUTOR = 'Jane Smith');


SELECT ID_CATEGORIA, CATEGORIA, COUNT(CATEGORIA_LIVRO.FK_CATEGORIA)
FROM CATEGORIA
INNER JOIN CATEGORIA_LIVRO ON CATEGORIA.ID_CATEGORIA = CATEGORIA_LIVRO.ID_CATEGORIA_LIVRO
GROUP BY ID_CATEGORIA, CATEGORIA;


SELECT AUTOR.NOME_AUTOR, COUNT(LIVRO.ISBN) AS QUANTIDADE_LIVRO
FROM AUTOR
INNER JOIN AUTOR_LIVRO ON AUTOR.ID_AUTOR = AUTOR_LIVRO.ID_AUTOR_LIVRO
INNER JOIN LIVRO ON AUTOR_LIVRO.ID_AUTOR_LIVRO = LIVRO.ISBN
GROUP BY AUTOR.ID_AUTOR;


SELECT CATEGORIA.CATEGORIA AS NOME_CATEGORIA, COUNT(LIVRO.ISBN) AS QUANTIDADE_LIVROS
FROM CATEGORIA
INNER JOIN CATEGORIA_LIVRO ON CATEGORIA.ID_CATEGORIA = CATEGORIA_LIVRO.ID_CATEGORIA_LIVRO
INNER JOIN LIVRO ON CATEGORIA_LIVRO.ID_CATEGORIA_LIVRO = LIVRO.ISBN
GROUP BY CATEGORIA.ID_CATEGORIA
HAVING COUNT(LIVRO.ISBN) = 1;


SELECT *
FROM LIVRO
ORDER BY DATA_PUBLICACAO ASC
LIMIT 1;


SELECT 
    EXTRACT(MONTH FROM DATA_REGISTRO) AS MES,
    COUNT(*) AS QUANTIDADE_USUARIOS
FROM 
    USUARIO
WHERE 
    EXTRACT(YEAR FROM DATA_REGISTRO) = 2024
GROUP BY 
    EXTRACT(MONTH FROM DATA_REGISTRO)
ORDER BY 
    MES;


SELECT LIVRO.TITULO AS LIVRO_MENOS_EMPRESTADO, COUNT(EMPRESTIMO.FK_LIVRO) AS TOTAL_EMPRESTIMOS
FROM LIVRO
INNER JOIN EMPRESTIMO ON LIVRO.ISBN = EMPRESTIMO.FK_LIVRO
GROUP BY LIVRO.ISBN, LIVRO.TITULO
ORDER BY TOTAL_EMPRESTIMOS ASC;


SELECT LIVRO.TITULO AS LIVRO_MAIS_EMPRESTADO, COUNT(EMPRESTIMO.FK_LIVRO) AS TOTAL_EMPRESTIMOS
FROM LIVRO
INNER JOIN EMPRESTIMO ON LIVRO.ISBN = EMPRESTIMO.FK_LIVRO
GROUP BY LIVRO.ISBN, LIVRO.TITULO
ORDER BY TOTAL_EMPRESTIMOS DESC;


SELECT SUM(IDADE) AS SOMA_IDADES,
       AVG(IDADE) AS MEDIA_IDADES 
FROM AUTOR;


SELECT * 
FROM LIVRO
ORDER BY DATA_PUBLICACAO DESC
LIMIT 3;


SELECT COUNT(*) AS total_emprestimos_premium
FROM EMPRESTIMO
INNER JOIN USUARIO ON EMPRESTIMO.FK_USUARIO = USUARIO.ID_USUARIO
INNER JOIN ASSOCIACAO ON USUARIO.FK_ASSOCIACAO = ASSOCIACAO.ID_ASSOCIACAO
WHERE ASSOCIACAO.ASSOCIACAO = 'PREMIUM';


SELECT AUTOR.NOME_AUTOR AS NomeAutor, COUNT(LIVRO.ISBN) AS NumeroLivros
FROM AUTOR
INNER JOIN AUTOR_LIVRO ON AUTOR.ID_AUTOR = AUTOR_LIVRO.FK_AUTOR
INNER JOIN LIVRO ON AUTOR_LIVRO.FK_LIVRO = LIVRO.ISBN
GROUP BY AUTOR.NOME_AUTOR;


SELECT CATEGORIA.CATEGORIA AS NomeCategoria, COUNT(EMPRESTIMO.ID_EMPRESTIMO) AS NumeroLivrosEmprestados
FROM CATEGORIA
INNER JOIN CATEGORIA_LIVRO ON CATEGORIA.ID_CATEGORIA = CATEGORIA_LIVRO.FK_CATEGORIA
INNER JOIN LIVRO ON CATEGORIA_LIVRO.FK_ISBN = LIVRO.ISBN
INNER JOIN EMPRESTIMO ON LIVRO.ISBN = EMPRESTIMO.FK_LIVRO
GROUP BY CATEGORIA.CATEGORIA;


WITH EmprestimosPorUsuario AS (
  SELECT
    e.fk_usuario,
    COUNT(DISTINCT e.fk_livro) AS qtd_livros
  FROM emprestimo e
  GROUP BY e.fk_usuario
)
SELECT
  u.*,
  epu.qtd_livros
FROM usuario u
JOIN EmprestimosPorUsuario epu ON u.id_usuario = epu.fk_usuario
ORDER BY epu.qtd_livros DESC
LIMIT 1;


SELECT AVG(DATEDIFF(data_devolucao, data_retirada)) AS media_dias
FROM emprestimo;


SELECT livro.*
FROM livro
LEFT JOIN emprestimo ON livro.ISBN = emprestimo.fk_livro
WHERE emprestimo.fk_livro IS NULL;


SELECT categoria.categoria, COUNT(categoria_livro.fk_ISBN) AS numero_de_livros
FROM categoria
JOIN categoria_livro ON categoria.id_categoria = categoria_livro.fk_categoria
JOIN livro ON categoria_livro.fk_ISBN = livro.ISBN
GROUP BY categoria.id_categoria
ORDER BY numero_de_livros DESC
LIMIT 1;


SELECT MONTH(data_retirada) AS mes, COUNT(*) AS quantidade_emprestimos
FROM emprestimo
GROUP BY mes
HAVING quantidade_emprestimos > 5;


SELECT usuario.*
FROM usuario
JOIN emprestimo ON usuario.id_usuario = emprestimo.fk_usuario
WHERE MONTH(usuario.data_registro) = MONTH(emprestimo.data_retirada);


SELECT * 
FROM AUTOR
ORDER BY IDADE ASC
LIMIT 1;


